### ISSUE TITLE
Your release gives an error

### ISSUE THREAD

**Issue by mzeinstra** [SabrinaVerhage/CultureDataGO#1]
Hi Sabrina,

The release gives an error on mac. Did it perhaps not include all dependancies?

![image](https://cloud.githubusercontent.com/assets/5627431/22200167/4507541e-e15e-11e6-9666-be95dfb94f49.png)

**Comment by SabrinaVerhage** [comment]
Hm seems to be a zip problem -I updated the mac release, does it work now?

**Comment by mzeinstra** [comment]
Unfortunately the app gives the same error:

![image](https://cloud.githubusercontent.com/assets/5627431/25129591/00e35b88-243f-11e7-8a7a-e13fcde989d5.png)


It is not the zip but the app that gives this error.

**Comment by mzeinstra** [comment]
Also looks like you did nu push the release?

![image](https://cloud.githubusercontent.com/assets/5627431/25129696/660477a4-243f-11e7-80ce-3402c3ca5351.png)

**Comment by SabrinaVerhage** [comment]
Ah, the error you are receiving is because the application is from an unidentified developer (aka me) https://support.apple.com/en-us/HT202491 http://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/ -Apple is getter more and more strict about this

The application runs on my side, however I am still running into issues with dependencies in relation to compression & upload. After download & decompression it runs but shows a grey screen only.

Releases work different from repositories; one can update a release without changing the release date :)
